openapi: 3.0.1
info:
  title: Password Validator
  description: ASP.NET Core Web API - Password Validation Application
  contact:
    name: Matheus Hafner
    url: https://github.com/mmhafner
    email: mmhafner@msn.com
  version: v1
paths:
  /PasswordValidator:
    post:
      tags:
        - PasswordValidator
      summary: "Validate the password to match the rules\r\n- Nine or more characters\r\n- At least one digit\r\n- At least one lowercase letter\r\n- At least one uppercase letter\r\n- At least one special character (Consider !@#$%^&*()-+ as special characters)\r\n- No repeated characters"
      requestBody:
        description: Password to validate
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/PasswordValidationResult'
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordValidationResult'
            text/json:
              schema:
                $ref: '#/components/schemas/PasswordValidationResult'
components:
  schemas:
    PasswordValidationErrorEnum:
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      type: integer
      format: int32
    PasswordValidationResult:
      type: object
      properties:
        success:
          type: boolean
        errors:
          type: array
          items:
            $ref: '#/components/schemas/PasswordValidationErrorEnum'
          nullable: true
      additionalProperties: false